name: Brew Formula Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_formula:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
      fail-fast: false

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    
    - name: Cache Homebrew dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew
          /home/linuxbrew/.cache/Homebrew
        key: ${{ runner.os }}-homebrew-${{ hashFiles('**/*.rb') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: Install dependencies
      run: |
        brew install cmake ccache petsc boost vc eigen hdf5-mpi
        brew install --build-bottle abhinavsns/homebrew-openfpm/parmetis
        brew install --build-bottle abhinavsns/homebrew-openfpm/libhilbert
        brew install --build-bottle abhinavsns/homebrew-openfpm/blitz
        brew install --build-bottle abhinavsns/homebrew-openfpm/algoim
        brew postinstall abhinavsns/homebrew-openfpm/parmetis
        brew postinstall abhinavsns/homebrew-openfpm/libhilbert
        brew postinstall abhinavsns/homebrew-openfpm/blitz
        brew postinstall abhinavsns/homebrew-openfpm/algoim

    - name: Test install formula
      run: |
        brew install --verbose --build-bottle ./openfpm.rb
        brew postinstall --verbose ./openfpm.rb

#    - name: Bottle formula
#      run: |
#        brew bottle abhinavsns/homebrew-openfpm/parmetis
#        brew bottle abhinavsns/homebrew-openfpm/libhilbert
#        brew bottle abhinavsns/homebrew-openfpm/blitz
#        brew bottle abhinavsns/homebrew-openfpm/algoim
#        brew bottle abhinavsns/homebrew-openfpm/openfpm

#    - name: Upload bottles
#      uses: actions/upload-artifact@v2
#      with:
#        name: bottles
#        path: "*.bottle.*.tar.gz"
